# The multiplier of the speed, this must be an integer or float greater than 1.
# A multiplier of 3 means that all the projectiles will travel 300% faster.
speed-multiplier: 3

# Increase the gravity of the projectiles here.
# A multiplier of 3 means that all the projectiles will have 300% more gravity.
gravity-multiplier: 3